### ISSUE TITLE
!GetAtt YAML tag support?

### ISSUE THREAD

**Issue by grahamjenson** [awslabs/goformation#152]
Will there be !GetAtt support, or is this impossible?

In `intrinsics/fngetatt.go` it just returns nil.

**Comment by rwade42** [comment]
Hi @grahamjenson  - were you able to figure this out? I'm running into an issue trying to use GetAtt as well.

**Comment by grahamjenson** [comment]
Yes, I submitted a PR that uses the base64 encoding. 

```
template, err := goformation.ParseYAMLWithOptions(input, &intrinsics.ProcessorOptions{
					IntrinsicHandlerOverrides: cloudformation.EncoderIntrinsics,
				})
```

**Comment by rwade42** [comment]
Ah that's awesome, thank you!
