### ISSUE TITLE
Forking/vendoring YAML packages

### ISSUE THREAD

**Issue by PaulMaddox** [awslabs/goformation#16]
As we've patched the go-yaml package, we need to:

1. Push new patched version to github.com/sanathkr/go-yaml
2. `govendor remove gopkg.in/yaml.v2 && rm -rf vendor/gopkg.in/yaml.v2`
3. `govendor fetch github.com/sanathkr/go-yaml`
4. Fork github.com/ghodss/yaml to github.com/sanathkr/yaml
5. Modify the fork to use github.com/sanathkr/go-yaml instead of gopkg.in/yaml.v2
6. `govendor remove github.com/ghodss/yaml && rm -rf vendor/github.com/ghodss/yaml`
7. `govendor fetch github.com/sanathkr/yaml`
8. Update imports in intrinsics/* to use github.com/sanathkr/yaml 

I think that's it - let me know if you can think of a better way.

**Comment by sanathkr** [comment]
This is done!
