### ISSUE TITLE
Question: Does this have any relationship with the CDK?

### ISSUE THREAD

**Issue by brad-jones** [awslabs/goformation#187]
The last couple of days I have been developing a new stack with the [CDK](https://github.com/awslabs/aws-cdk). Most of the rest of my code base is in `go` but the stack is developed in TypeScript. I just stumbled across this project now and I am thinking if it's worth making the switch.

Anyway from my quick comparison, this tool is only implementing the low level Cloud Formation Library and does not provide a higher level API like the CDK does with it's _"Constructs"_. Nor does it attempt to provide any commands like `deploy` & `diff`. It purely generates JSON or YAML documents. What you do with these is then up to you. All of which I am fine with.

I guess what I want to get an idea of is if this project has any longevity in it or is it likely to be dropped in favour of CDK?

**Comment by PaulMaddox** [comment]
I would stick with the CDK - it's a far more powerful concept as it can work at high level (e.g. packaging and publishing components or whole architectures) as well as the low level (auto-generated from CloudFormation specification). 

I think GoFormation is useful today when you have a Go application that wants to do low level CloudFormation manipulation, but in time (when CDK [adds Go support](https://github.com/awslabs/aws-cdk/issues/547)) I see this library being less relevant.
