### ISSUE TITLE
Enable EKS Control Plan logging to cloudwatch

### ISSUE THREAD

**Issue by StevenACoffman** [awslabs/goformation#198]
**Why do you want this feature?**
We want to see the EKS control plane logs for monitoring, troubleshooting, and security audit.

**What feature/behavior/change do you want?**
The ability to enable/disable in cloudformation, each of the [five control plane log types available in EKS](https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html):

* `api`
* `audit`
* `authenticator`
* `controllerManager`
* `scheduler`

Documentation on EKS control plane logging API and CLI commands:
https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html

`aws eks --region us-west-2 update-cluster-config --name prod \ --logging '{"clusterLogging":[{"types":["api","audit","authenticator","controllerManager","scheduler"],"enabled":true}]}'`

Ref: [aws/containers-roadmap#26](https://github.com/aws/containers-roadmap/issues/26)

API documentation: https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html

File to be modified: https://github.com/awslabs/goformation/blob/master/cloudformation/resources/aws-eks-cluster.go

**Comment by StevenACoffman** [comment]
Something like:
```
	Logging struct {
		ClusterLogging []struct {
			Enabled bool `json:"enabled"`
			Types   []string `json:"types"`
		} `json:"clusterLogging"`
	} `json:"logging"`
```
https://github.com/awslabs/goformation/blob/master/cloudformation/resources/aws-eks-cluster.go#L33

**Comment by StevenACoffman** [comment]
ref aws/containers-roadmap#242

**Comment by PaulMaddox** [comment]
As soon as this is in CloudFormation (and the new [resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) is published, we can get it included in goformation.

You can run `go generate` in your goformation repo directory to update goformation to the latest resource specification (EKS logging isn't there as of right now) - or wait for our CI job to automatically update goformation and release a new version.
