### ISSUE TITLE
goformation should be able to roundtrip SAM templates

### ISSUE THREAD

**Issue by evantorrie** [awslabs/goformation#199]
Currently, I want to read in a SAM template - that may or may not use the SAM specific Globals resource. Then, I change a couple of attributes on one of the resources. Currently this fails (even with `&ProcessorOptions{NoProcess: true}`, because a cloudformation.Template doesn't have a way to represent the Globals section.

I would even be happy if it would resolve the globals (as it looks like it currently does), but leave the rest untouched - something like `&ProcessorOptions{ProcessOnlyGlobals: true}` - where such an option does process the globals but leaves the handlers/conditions/Fn intrinsics unchanged.

Is this something that seems reasonable to add?

**Comment by PaulMaddox** [comment]
This was fixed in #376, and released in Goformation v5.0.0 today.
See the PR description for more information. 

Thanks
