### ISSUE TITLE
Missing resource definition VPCEndpointService

### ISSUE THREAD

**Issue by kbessas** [awslabs/goformation#207]
Hello,

The resource definition for the `VPCEndpointService` seems to be missing.

Reference:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html
https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
https://github.com/awslabs/goformation/tree/master/cloudformation/resources

**Comment by PatMyron** [comment]
@kbessas shouldn't be missing anymore :)

**Comment by PaulMaddox** [comment]
Closing out this old issue - VPCEndpointService has been in goformation for a while now. 

https://github.com/awslabs/goformation/blob/master/cloudformation/ec2/aws-ec2-vpcendpointservice.go
