### ISSUE TITLE
Too many files in goformation/cloudformation/resources folder

### ISSUE THREAD

**Issue by weijinw** [awslabs/goformation#218]
There are >1000 go files in folder goformation/cloudformation/resources folder. This is too many for bazel build (https://github.com/bazelbuild/rules_go/issues/2002) and also the list is too long in git and any code review system. Is it possible to have the files in different sub folders, ./ec2, ./sns, etc.

**Comment by PaulMaddox** [comment]
> Is it possible to have the files in different sub folders, ./ec2, ./sns, etc?

I've done exactly this in v3.0.0 of goformation (just released). 
Sorry it took so long.
