### ISSUE TITLE
Condition in statement is generating template json with null Statement

### ISSUE THREAD

**Issue by Nishant-Pathak** [awslabs/goformation#222]
First of all I would like to that for providing such an awesome library, we earlier had our custom implementation and now we are migrating to use go formation.

We have one use case to provide condition is IAM statement.
While generating a template json, it creates with a null statement. Is this known issue?

![image](https://user-images.githubusercontent.com/724049/64664898-49bb1800-d46e-11e9-9e95-9779b5754dc1.png)

**Comment by PaulMaddox** [comment]
Hi @Nishant-Pathak - can you provide a more detailed example so that I can replicate it here and write a fix/test for it? Thanks.

**Comment by alock** [comment]
I had a similar issue and when attempting to write an example in https://play.golang.org found my bug.  I was pulling v4 iam with `"github.com/awslabs/goformation/v4/cloudformation/iam"`, but I was still pulling v1 with `"github.com/awslabs/goformation/cloudformation"` right above it.  After changing my cloudformation import to `"github.com/awslabs/goformation/v4/cloudformation` Conditions work! 

@Nishant-Pathak might be something to check.

**Comment by PaulMaddox** [comment]
Support for conditions has now been included in v4.3.0
