### ISSUE TITLE
project build fails

### ISSUE THREAD

**Issue by gliptak** [awslabs/goformation#240]
https://travis-ci.org/awslabs/goformation/jobs/604107459#L398
```
# github.com/gaocegege/maintainer/contributing
../../../gopath/pkg/mod/github.com/gaocegege/maintainer@v1.0.5/contributing/contributing.go:109:47: not enough arguments in call to client.Repositories.Get\
	have (string, string)
	want (context.Context, string, string)
```

**Comment by PaulMaddox** [comment]
Hi @gliptak,

I recently switched this repo away from TravisCI to GitHub Actions.
Where did you notice the builds failing? Was it the badge on the README? 

Paul

**Comment by gliptak** [comment]
@PaulMaddox thanks, I see the Travis badge was removed. I will review your new Actions based setup
