### ISSUE TITLE
`ReturnData: false` in the CloudWatch Data Metrics should not be omitted

### ISSUE THREAD

**Issue by Trane9991** [awslabs/goformation#255]
If it is omitted CloudFormation template update with fail with the error: `Exactly one element of the metrics list should return data`, because  all the omitted values assumed as `True`

From the [AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-alarm-metricdataquery.html):

**ReturnData**
This option indicates whether to return the timestamps and raw data values of this metric. If you are performing this call just to do math expressions and do not also need the raw data returned, you can specify False. **If you omit this, the default of True is used.**

I created PR #254, and then realized that this code is autogenerated.
Please take apply the needed fix on your side, thanks!

**Comment by manuel-trejo-rico** [comment]
I have the same error because of ReturnData. The only workaround that worked for me is to use goformation lib as a vendor and modify Alarm_MetricDataQuery struct so it uses a *bool instead of a bool. This way, if not set it is omitted but if it is a pointer to false it is not omitted and the generated stack has a ReturnData = false field.

**Comment by manuel-trejo-rico** [comment]
Similar issue happens with [UserPool Mutable field](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-schemaattribute.html#cfn-cognito-userpool-schemaattribute-mutable), if you set it to false it is omitted.

In general, I think that it would be a good idea to modify all the bool fields to be pointers to bool (*bool).

**Comment by xrn** [comment]
@rubenfonseca if I am correct this would be solved in v6 looking on behaviour of my issue - https://github.com/awslabs/goformation/issues/474
