### ISSUE TITLE
CustomResources do not respect DependsOn

### ISSUE THREAD

**Issue by Sayan-** [awslabs/goformation#270]
**This is an issue in v4**

CustomResources still follow the pattern in https://github.com/awslabs/goformation/issues/132. The goformation library has since changed to using field types and custom JSON marshal/unmarshal in https://github.com/awslabs/goformation/issues/245.

This is problematic when I attempt to create a `CustomResource` in a `Template`. The `DependsOn` will never be populated correctly during a `Template.YAML()` or `Template.JSON()` call. 

Additionally, there are actually two versions of `CustomResources` in this library:

in: `github.com/awslabs/goformation/v4/cloudformation`
https://github.com/awslabs/goformation/blob/785575a39be4e3730b3fe97b04c17b8007ab9358/cloudformation/custom_resource.go#L9-L22

vs

in: `github.com/awslabs/goformation/v4/cloudformation/cloudformation`
https://github.com/awslabs/goformation/blob/785575a39be4e3730b3fe97b04c17b8007ab9358/cloudformation/cloudformation/aws-cloudformation-customresource.go#L11-L31

**Comment by xrn** [comment]
Hi @Sayan- 

I am not sure if this is 100% correct solution but please check this:

`package x

import (
	"github.com/awslabs/goformation/v4/cloudformation"
	cloudformationResource "github.com/awslabs/goformation/v4/cloudformation/cloudformation"
)

func TestFunction(t *cloudformation.Template) {

	// Add RDS Aurora cluster - Platform DB
	t.Resources["CustomResourceName"] = &cloudformationResource.CustomResource{
		ServiceToken: "x",
	}
}
`

cc: @PaulMaddox

**Comment by douglas-gibbons-lark** [comment]
Here's a simple example, showing the issue:

```
package main

import (
	"io/ioutil"

	"github.com/awslabs/goformation/v4/cloudformation"
)

func main() {
	c := &cloudformation.CustomResource{
		Type: "AWS::Something::Someting",
		Properties: map[string]interface{}{
			"Foo": "Bar",
		},
	}

       // This sets the _depondsOn private field which is never Marshaled into JSON
	c.SetDependsOn([]string{"OtherResource"})

	t := cloudformation.NewTemplate()
	t.Resources["customResource"] = c

	j, _ := t.JSON()
	ioutil.WriteFile("/tmp/stack.json", j, 0644)
}
```
This outputs:
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "customResource": {
      "Properties": {
        "Foo": "Bar"
      },
      "Type": "AWS::Something::Somehting"
    }
  }
}
```

i.e. It's missing `DependsOn`.

**Comment by sgavulla** [comment]
I can confirm that DependsOn is missing as mentioned by @douglas-gibbons-lark. This  is needed otherwise our stack creation fails (the custom resource for our stack dependsOn a DDB table to be created first).

**Comment by xrn** [comment]
Let's close it :confetti_ball:

**Comment by Sayan-** [comment]
Amazing! Thank you @xrn - I entirely forgot about this thread.
