### ISSUE TITLE
Cloudfront default cache behaviour with 'minTTL = 0' is omitted

### ISSUE THREAD

**Issue by manuel-trejo-rico** [awslabs/goformation#273]
In [Cloudfront Default Cache Behaviour MinTTL](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html#cfn-cloudfront-distribution-defaultcachebehavior-minttl), if you set '0' to forward all the headers the value is omitted. Changing from float64 to *float64 fix it.

I think that this issue is related to #255 because both can be fixed the same way, changing from a primitive type to a pointer to a primitive type.

**Comment by xrn** [comment]
@rubenfonseca if I am correct this would be solved in v6 looking on behaviour of my issue - https://github.com/awslabs/goformation/issues/474

**Comment by rubenfonseca** [comment]
Thanks!
