### ISSUE TITLE
CloudFormation Schema Issues

### ISSUE THREAD

**Issue by PaulMaddox** [awslabs/goformation#300]
The latest CloudFormation schema published (2020-08-25) has two issues:

`AWS::ECR::Repository.RepositoryPolicyText` has no `PrimiviteType` (or any type).
`AWS::KMS::Key.KeyPolicy` has no `PrimitiveType` (or any type).

```
"AWS::ECR::Repository": {
  "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html",
  "Properties": {
    "RepositoryPolicyText": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-repositorypolicytext",
      "UpdateType": "Mutable",
      "Required": false
    },
```

```
"AWS::KMS::Key": {
  "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html",
  "Properties": {
    "KeyPolicy": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#cfn-kms-key-keypolicy",
      "UpdateType": "Mutable",
      "Required": true
    },
```

source: https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

This causes tests to fail after code generation: 

```
❯ go test ./...
# github.com/awslabs/goformation/v4/cloudformation/ecr
cloudformation/ecr/aws-ecr-repository.go:39:24: undefined: Repository_
# github.com/awslabs/goformation/v4/cloudformation/kms
cloudformation/kms/aws-kms-key.go:34:13: undefined: Key_
```

Ticket raised with CloudFormation team to have this corrected.

**Comment by xrn** [comment]
@PaulMaddox this could be probably closed

**Comment by PaulMaddox** [comment]
This still has not been resolved upstream in the CloudFormation Resource Specification. 

I have put in place a workaround in #314. Instead of blocking resource generation when properties are found with missing type information, we instead set the type to `Json`. This in turn will set the property type to `interface{}` in the generated Go structs.

This is an example of the output where the autofixing is logged:

```
❯ go generate
GoFormation Resource Generator
Downloading cloudformation specification from https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
Warning: auto-fixing missing property type to 'Json' for http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#cfn-kms-key-keypolicy
Warning: auto-fixing missing property type to 'Json' for http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-repositorypolicytext
```

**Comment by PatMyron** [comment]
[`AWS::MediaPackage::PackagingConfiguration` similar in `19.0.0`](https://github.com/aws-cloudformation/cfn-python-lint/pull/1751)

**Comment by xrn** [comment]
@rubenfonseca I believe this is solved as well all resources have PrimitiveType

**Comment by rubenfonseca** [comment]
Thanks!
