### ISSUE TITLE
Add support for AWS SAM globals in the schema

### ISSUE THREAD

**Issue by hunterwerlla** [awslabs/goformation#305]
The IntelliJ IDE uses `https://github.com/awslabs/goformation/blob/master/schema/sam.schema.json` for `sam` files, but this schema still does not support the `Globals` section. 

We had a customer report this issue in our repo https://github.com/aws/aws-toolkit-jetbrains/issues/1466

**Comment by PaulMaddox** [comment]
This was fixed in #376, and released in Goformation v5.0.0 today.
