### ISSUE TITLE
Update schema is broken (missing AWS::CloudFront::CachePolicy)

### ISSUE THREAD

**Issue by ibrt** [awslabs/goformation#313]
Hi I was looking for `AWS::CloudFront::CachePolicy` and realized it's missing. Tried to regenerate locally and got this error:

```
ERROR: Failed to generate resources: the following resource properties have no type information in the CloudFormation Resource Specification:
	AWS::ECR::Repository.RepositoryPolicyText
	AWS::KMS::Key.KeyPolicy
```

Then I also realized your Update Schema GitHub action has been broken since Aug 24th. Any chance to get it fixed?

**Comment by PaulMaddox** [comment]
The upstream CloudFormation Resource Specification issues have still not been resolved. I am working with the CFN team to fix this.

In the meantime I have  implemented a workaround in goformation, that sets the type of any unknown properties to `interface{}`. For the two current properties (`AWS::ECR::Repository.RepositoryPolicyText` and `AWS::KMS::Key.KeyPolicy`) this is the correct type, and does not cause any compatibility issues.

I updated goformation with all of the latest CloudFormation changes in PR #320, and the GitHub automation has cut a new version of goformation: v4.15.2 with all of the new resources.

**Comment by PaulMaddox** [comment]
https://github.com/awslabs/goformation/blob/9c689033422feaf5f8431dee3c2ff377e6ea474c/cloudformation/cloudfront/aws-cloudfront-cachepolicy.go#L11-L34
