### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SamuelTissot** [awslabs/goformation#34]
Hello,

Thanks you for the library !!

I was wondering if there was documentation with examples that were planned / released ?

If not is there a process in place to submit documentation?

- format
- structure of exampels .
- PR's 
- etc

Thanks

**Comment by PaulMaddox** [comment]
Hi @SamuelTissot, as with most Go libraries, there is documentation automatically generated by GoDoc:

http://godoc.org/github.com/awslabs/goformation

This is linked to from the README.
There's also some examples in the README of how to use the library.

**Comment by SamuelTissot** [comment]
Thanks for the quick response.
