### ISSUE TITLE
No Type in marshaled JSON/YAML

### ISSUE THREAD

**Issue by billyshambrook** [awslabs/goformation#35]
Maybe I am missing something, but in your example of marshaling JSON/YAML, the output does not contain the `Type` field under each resource. Is this expected? Thanks!

**Comment by billyshambrook** [comment]
Ok, figured it out...

In this [example](https://github.com/awslabs/goformation#marshalling-cloudformationsam-described-with-go-structs-into-yamljson), you need to add each resource as a pointer, for it's MarshalJSON method to be called...

```
...
    template.Resources["MyRoute53HostedZone"] = &cloudformation.AWSRoute53HostedZone{
        Name: "example.com",
    }
...
```

**Comment by PaulMaddox** [comment]
Thanks @billyshambrook - that's a good spot. The API changed slightly after writing those examples and I didn't go back and update them. I'll get that sorted.
