### ISSUE TITLE
struct DBInstance : AutoMinorVersionUpgrade omits if false

### ISSUE THREAD

**Issue by gregory-v** [awslabs/goformation#416]
Hi, 

AutoMinorVersionUpgrade is bool, when you set the AutoMinorVersionUpgrade to false value (AutoMinorVersionUpgrade:    false) ,the property is removed from the templateBody like encoding/json: Marshaller omits false booleans.

AutoMinorVersionUpgrade  should *bool

**Comment by rubenfonseca** [comment]
Hello. We believe the issue was solved on v6.0.0 https://github.com/awslabs/goformation/releases/tag/v6.0.0. Closing this issue for now. Please reopen if you have other issues!
