### ISSUE TITLE
Parsing CloudFormation Template with int/String values in YAML/JSON

### ISSUE THREAD

**Issue by bruceliqin** [awslabs/goformation#506]
When parsing TaskCPU/TaskMemory/ContainerPort, the expected formats are int/int/string. However, the parser is unable to read in INTs from a YAML and the JSON parameter list defaults as String so COntainerPort, which is supposed to be an int causes a problem. Is there a solution to this existing in the library?

**Comment by rubenfonseca** [comment]
Hi @bruceliqin can you please provide us with an example template that you're trying to parse, and the expected/unexpected output?
