### ISSUE TITLE
DBClusterParameterGroupName missing from DBClusterParameterGroup type

### ISSUE THREAD

**Issue by chrisdostert** [awslabs/goformation#519]
Per [AWS cloudformation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbclusterparametergroup.html#cfn-rds-dbclusterparametergroup-dbclusterparametergroupname) the DBClusterParameterGroup type supports a DBClusterParameterGroupName property. The [generated goformation types](https://github.com/awslabs/goformation/blob/658bf78b3cee73d6047e2718f4223df00fba0188/cloudformation/rds/aws-rds-dbclusterparametergroup.go#L15) however do not seem to include the property

**Comment by rubenfonseca** [comment]
Hi @chrisdostert we've added support for the mentioned field on today's 7.0.6 release! Thank you for your patience :)
