### ISSUE TITLE
Support for AWS::Scheduler::Schedule

### ISSUE THREAD

**Issue by xrn** [awslabs/goformation#523]
@rubenfonseca is there a chance that you will update goformation in that way that we have a support for https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedule.html ?

**Comment by rubenfonseca** [comment]
Hi @xrn, we fixed the build process and added support for AWS::Scheduler::Schedule on version 7.0.6! Thank you for your patience :)
