### ISSUE TITLE
MinValue and MaxValue from a parsed parameter are ambiguous

### ISSUE THREAD

**Issue by rclark** [awslabs/goformation#542]
I'm trying to parse a template parameter in order to provide a user with a prompt on the command line. Once they've entered a value, I would like to validate that it is appropriate. If the parameter type is `"Number"`, then I would need to check:

1. that the user entered a numeric value, and
2. if the template file defined a `MinValue` and/or `MaxValue` for the parameter, 
3. then the user's numeric value falls between the defined min/max.

https://github.com/awslabs/goformation/blob/bf80608c482dde15129c70dd7175c74f143fd5bf/cloudformation/template.go#L36-L37

These fields are `float64`, which means that even if the optional properties are not present in the template file, the fields will get a zero-value of `0`. 

So the trouble is, I can't differentiate between a parameter where there is no defined `MinValue`, or a parameter where there is a defined `MinValue` of `0`.

**Comment by rclark** [comment]
https://github.com/awslabs/goformation/blob/bf80608c482dde15129c70dd7175c74f143fd5bf/cloudformation/template.go#L34-L35

The same problem exists for validating the length of a `"String"` or `"List"` type of parameter.

**Comment by rubenfonseca** [comment]
Hi @rclark, looking at this now.

**Comment by xrn** [comment]
This can be closed
