### ISSUE TITLE
Intrinsic Function Long form to short form after new update

### ISSUE THREAD

**Issue by bruceliqin** [awslabs/goformation#551]
Parsing the below template functions normally until the recent update to the new GoLang Version:
`!Join [!Ref Param1, "Val2"]` -> `Fn::Join: [Ref: Param1 Val2]`

After the new update, it fails to parse the Ref Intrinsic function and outputs the below:
`Fn::Join:[Param1 Val2]`

**Comment by rubenfonseca** [comment]
@bruceliqin thank you so much for reporting this. We're a little pressed on time, so one thing that could help us immensely would be to provide us with a snippet of code where you parse a sample template that clearly shows the failing case.

Would you be able to help us with this?

**Comment by scottiedog45** [comment]
If someone picks this up, there is some example code on a [possibly related issue](https://github.com/awslabs/goformation/issues/554) I posted

**Comment by bruceliqin** [comment]
I am using the below code as I would like to preserve the intrinsic functions:

	var test map[string]interface{}
	opts := &intrinsics.ProcessorOptions{
		NoProcess: true,
	}
	output, _ := intrinsics.ProcessYAML(testData, opts)

**Comment by bruceliqin** [comment]
I am expecting 

!Join [!Ref Param1, "Val2"] -> Fn::Join: [Ref: Param1 Val2]

But instead I get Fn::Join:[Param1 Val2]

**Comment by bruceliqin** [comment]
Hello, wanted to see if there is any updates on this issue
