### ISSUE TITLE
Handling AWS SAM's polymorphic properties (e.g. CodeUri)

### ISSUE THREAD

**Issue by PaulMaddox** [awslabs/goformation#6]
### Problem Statement

The AWS SAM specification has some fields that are polymorphic (aka, they can accept multiple types). A good example of this is the [AWS::Serverless::Function.CodeUri](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction) property, which can accept either a string, or an [S3 Object Location](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3-location-object).

There are two challenges with this:

#### 1. Defining polymorphism in a machine readable schema

Currently, v0.1.0 reads all resources from the [AWS CloudFormation Resource Specification](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html), and generates the Go files with the required structs for unmarshalling.

As AWS CloudFormation doesn't have any resources with polymorphic properties, the [specification format](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification-format.html) doesn't include the ability to define them.

The specification currently uses the following fields for defining a property's type:

```javascript
"PropertyName": {

    // If the property type is a single item of a primitive type, this will be used
    PrimitiveType: "",
    
    // If the property type is a map or list of a primitive type, this will be used
    PrimitiveItemType: ""

    // If the property type is a single item of a custom type, this will be used
    Type: "SomeCustomType",

    // If the property type is a map or list of a custom type, this will be used
    ItemType: "SomeCustomType"

}
```

#### 2. Unmarshalling polymorphic properties into Go structs

Currently, for each AWS CloudFormation resource, Goformation auto-generates a struct with all of it's properties, like so:

```go
// AWSLambdaFunction CloudFormation Resource (AWS::Lambda::Function)
type AWSLambdaFunction {
    Runtime string
    CodeUri string
    VpcConfig AWSServerlessFunction_VpcConfig
}

// AWSServerlessFunction_VpcConfig custom type
type AWSServerlessFunction_VpcConfig {
    SecurityGroupIds []string
    SubnetIds []string
}
```

This approach will not work for polymorphic properties such as CodeUri, which can be specified as a string, or S3 Bucket. This would cause the unmarshalling to fail for CodeUri above if an S3 Location was provided.

### Implementation

In order to describe the AWS SAM language specification in a machine readable format, I propose we extend the [AWS CloudFormation Resource Specification Format](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification-format.html) to include the following new fields:

```javascript
{
    PrimitiveTypes: [ "String", "Number" ],
    PrimitiveItemTypes: [ "String", "Number"]
    Types: [ "SomeCustomType" ],
    ItemTypes: [ "SomeCustomType" ],
} 
```

These 4 new fields would allow us to describe polymorphic properties that allow multiple variations of primitives, lists/maps of primitives, custom types and lists/maps of custom types.

For example, to describe the [AWS::Serverless::Function.CodeUri](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction) property, we could use:

```javascript
{
    "ResourceSpecificationVersion": "2016-10-31",
    "ResourceTypes": {
        "AWS::Serverless::Function": {
            "Documentation": "https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction",
            "Properties": {
                "CodeUri": {
                    "Documentation": "https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction",
                    "Required": true,
                    "PrimitiveTypes": [ "String" ],
                    "Types": [ "S3Location" ],
                    "UpdateType": "Immutable"
                },
                ...
            }
        }
    },
    "PropertyTypes": {
        "AWS::Serverless::Function.S3Location": {
            "Documentation": "https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3-location-object",
            "Properties": {
                "Bucket": {
                    "Documentation": "https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3-location-object",
                    "Required": true,
                    "PrimitiveType": "String",
                    "UpdateType": "Immutable"
                },
                "Key": {
                    "Documentation": "https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3-location-object",
                    "Required": true,
                    "PrimitiveType": "String",
                    "UpdateType": "Immutable"
                },
                "Version": {
                    "Documentation": "https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3-location-object",
                    "Required": false,
                    "PrimitiveType": "Integer",
                    "UpdateType": "Immutable"
                }
            }
        }
    }
}
```

This helps us with challenge 2: unmarshalling of polymorphic types into Go structs. It allows us to auto-generate a struct, and helper struct like so:

```go
// AWSServerlessFunction AWS CloudFormation Resource (AWS::Serverless::Function)
// See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
type AWSServerlessFunction struct {

	// CodeUri AWS CloudFormation Property
	// Required: true
	// See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
	CodeUri AWSServerlessFunction_StringOrS3Location `json:"CodeUri"`

    ...

}

// AWSServerlessFunction_StringOrS3Location is a helper struct that can hold either String or S3Location values
type AWSServerlessFunction_StringOrS3Location struct {
	String string
	S3Location AWSServerlessFunction_S3Location
}

// AWSServerlessFunction_S3Location AWS CloudFormation Resource (AWS::Serverless::Function.S3Location)
// See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3-location-object
type AWSServerlessFunction_S3Location struct {

	// Bucket AWS CloudFormation Property
	// Required: true
	// See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
	Bucket string `json:"Bucket"`

	// Key AWS CloudFormation Property
	// Required: true
	// See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
	Key string `json:"Key"`

	// Version AWS CloudFormation Property
	// Required: true
	// See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
	Version int `json:"Version"`
}
```

### Proposed Actions

1. The above has been implemented (with tests), I will submit a pull request shortly. I've only implemented AWS::Serverless::Function, and only a few primitive and one polymorphic property in the specification.
2. Update SAM deployment pipeline to auto-generate and publish a schema to S3/CloudFront 
3. Speak with CloudFormation team to see if they feel updating the main schema to support polymorphism would be appropriate, or whether we should continue to publish the AWS SAM specification separately.

### Reference Information

[AWS Serverless Application Model Specification](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md)

[AWS CloudFormation Resource Specification](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html)

[AWS CloudFormation Resource Specification Format](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification-format.html)

**Comment by PaulMaddox** [comment]
Here you can see the tests, which give a good idea of how this would appear to goformation consumers:

https://github.com/PaulMaddox/goformation/blob/54f09892a83bdc67baba8f397bb6ba95a84e2067/goformation_test.go

**Comment by sanathkr** [comment]
This is great! Does it support both single type notation and polymorphic type notations?

Also, when there are polymorphic types, all but one property in the type's strict will be nil, right? Like CodeUri will have string = nil if S3Bucket was used. Correct?
