### ISSUE TITLE
Zero values vs null values

### ISSUE THREAD

**Issue by deoxxa** [awslabs/goformation#61]
This is just a dump of some thoughts I had while looking at this library. Feel free to ignore or take onboard.

> deoxxa [11:30 AM]
> hrmm, i do see some problems with it
> e.g. comparing https://godoc.org/github.com/awslabs/goformation/cloudformation#AWSRDSDBInstance and https://godoc.org/github.com/crewjam/go-cloudformation#RDSDBInstance
> the crewjam library uses pointers for just about everything, which means the default value is null, rather than the zero value for the type
> the aws library doesn't use pointers, so if you leave out a parameter, you'll get the zero value, which sometimes has a distinctly different meaning to null
> e.g. `PubliclyAccessible` there - if you leave it as null or don't put it in the template, it'll inherit its value from the vpc subnet group
> if you explicitly set it to `false`, it'll never be public
> likewise with `true`, it'll always be public
> but the way amazon have defined those struct types, if you set it to `false` it won't go into the template
> so if your subnet group has its default as `true`, and you set it to `false` in the struct, it'll end up being public

See for (reduced, simulated) example: https://play.golang.org/p/MJoSKm4ph2j

**Comment by neoandroid** [comment]
I've hit the same problem with the "Essential" property of a container definition. Is there a suggested solution? I'm happy to implement a workaround if you point me how we should resolve this issue.
Shouldn't these kind of fields be pointers? That way it should work as users expect.

**Comment by mumoshu** [comment]
@deoxxa @neoandroid Can we probably close this as resolved, as @majasb has contributed fixes for booleans and numbers in #133?

**Comment by karnauskas** [comment]
Having similar problem:
```
			Monitoring: &cloudformation.AWSEC2LaunchTemplate_Monitoring{
				Enabled: false,
			},
```
is rendered as following in yaml output
```
        Monitoring: {}
```

**Comment by rhyselsmore** [comment]
I've had the same issue with the `AWSLogsSubscriptionFilter` type. It has a parameter named `FilterPattern`. In order to catch all events, you simply supply an empty string.

However, due to empty string being a null string in Go, the value is not included in the generated template.

**Comment by ndeloof** [comment]
ECS ContainerDefinition `Essential` attribute is not required and of type boolean, but then `omitempty` prevent to set value to `false`. Issue with that is that the actual API default is `true` : "If this parameter is omitted, a container is assumed to be essential.".
So there's no way to declare a non-essential containerdefinition

**Comment by PaulMaddox** [comment]
I think it's clear this library needs to transition to using pointers instead of values. It's causing a ton of rough edges. Unfortunately it may be a while before I have time to implement it, however if anyone else wants to have a go in the meantime i'll happily accept a PR.

**Comment by ndeloof** [comment]
AFAICT if you want to switch to pointers (like aws SDK does) you just need to change https://github.com/awslabs/goformation/blob/master/generate/property.go#L212 so that it uses `*xxx` instead of `x`, right?
I can prepare a PR for this purpose

**Comment by rubenfonseca** [comment]
That's right! Thank you for pointing this our @xrn.
