### ISSUE TITLE
Support UseOnlineResharding UpdatePolicy for ElastiCache ReplicationGroup

### ISSUE THREAD

**Issue by prajwal-swiggy** [awslabs/goformation#610]
The struct in https://github.com/awslabs/goformation/blob/ebd10494d7f1a10c071fe1b45acdaa4013f88da2/cloudformation/policies/policies.go#L52 needs to be updated to include the below property:
```	
// UseOnlineResharding if set to true updates the AWS::ElastiCache::ReplicationGroup without replacement.
UseOnlineResharding bool `json:"UseOnlineResharding,omitempty"`
```
Ref: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#:~:text=Required%3A%20No-,UseOnlineResharding%20policy,-To%20modify%20a

**Comment by rubenfonseca** [comment]
Closing as resolved
