### ISSUE TITLE
Skip Processing Intrinsic Functions

### ISSUE THREAD

**Issue by parsnips** [awslabs/goformation#62]
Hello,

Thanks for creating goformation, it has a lot of potential!

Currently parsing a template _requires_ evaluation of intrinsic functions and those will only resolve if there are local parameters present otherwise to `nil` (eg `Fn::Sub`).

That behavior seems fine for some uses, but when attempting to use goformation as a parser/generator this isn't as helpful, since many parameters will not be available in the template and I want to _preserve_ the intrinsic.

I'd like to be able to completely disable intrinsic evaluation and just leave the functions in place in the template..

Example parsing this bit:

```yaml
Location:
  Fn::Sub: "s3://${BucketName}/codebuild/builds/${Revision}/${Service}/api.yaml"
```

And then calling `template.YAML()` should leave the instrinsic in place and output:

```yaml
Location:
  Fn::Sub: "s3://${BucketName}/codebuild/builds/${Revision}/${Service}/api.yaml"
```

~Looking at the code, a handler like:~

```go
func reallyNonResolvingHandler(name string, input interface{}, template interface{}) interface{} {
	return template
}
```

~Does the trick when providing an override... I propose this is a better default `nonResolvingHandler`.  Thoughts?~

I now realize `template` has the entire tree.. I pushed up a proper fix which skips the intrinsic search altogether.

**Comment by parsnips** [comment]
After hacking around and thoroughly reading up https://github.com/awslabs/goformation/issues/3 I'll use an alternative approach outside modifying goformation.

**Comment by Pheels** [comment]
Can you please detail what your alternate approach was? I am also looking to process my template whilst keeping the intrinsic functions intact. I have raised the following issue:

https://github.com/awslabs/goformation/issues/302

**Comment by parsnips** [comment]
@Pheels this issue is a blast from the past.

Internally goformation encodes it's own intrinsics as json inside base64 strings... and when writing back to yaml it decodes and writes them out.

https://github.com/awslabs/goformation/blob/5f66a0da42693b974bded86fab50de4b123ed811/intrinsics/intrinsics.go#L258-L266

I wrote an intrinsics resolver that just turned them into base64 encoded json strings on parse:

```golang
var overrides = map[string]intrinsics.IntrinsicHandler{
	"Fn::Base64":      jsonMakingHandler,
	"Fn::And":         jsonMakingHandler,
	"Fn::Equals":      jsonMakingHandler,
	"Fn::If":          jsonMakingHandler,
	"Fn::Not":         jsonMakingHandler,
	"Fn::Or":          jsonMakingHandler,
	"Fn::FindInMap":   jsonMakingHandler,
	"Fn::GetAtt":      jsonMakingHandler,
	"Fn::GetAZs":      jsonMakingHandler,
	"Fn::ImportValue": jsonMakingHandler,
	"Fn::Join":        jsonMakingHandler,
	"Fn::Select":      jsonMakingHandler,
	"Fn::Split":       jsonMakingHandler,
	"Fn::Sub":         jsonMakingHandler,
	"Ref":             jsonMakingHandler,
}

// Replaces intrinsic functions with base64 encoded json version of intrinsic function.
// Goformation's post processing of intrinsics will replace.
func jsonMakingHandler(name string, input interface{}, template interface{}) interface{} {
	intrinsicFunc := map[string]interface{}{
		name: input,
	}

	b, err := json.Marshal(intrinsicFunc)
	if err != nil {
		panic(err)
	}

	return base64.StdEncoding.EncodeToString(b)
}
```

There are some quirks iirc.... but since that time i've switched from using goformation to parse cloudformation templates, to using it write them... So ymmv.

**Comment by Pheels** [comment]
Yes, apologies for ressurecting an old thread, it just seemed interesting and possibly relevant to my own issue; thanks for the prompt response.

> // Goformation's post processing of intrinsics will replace.

Just to confirm my understanding - the template post-processing will still contain the complete intrinisic function, as opposed to the resolved value i.e.:
`FunctionName : !Sub '${SomeFunctionName'`

**Comment by parsnips** [comment]
Yes, exactly
