### ISSUE TITLE
Fn::GetAtt support

### ISSUE THREAD

**Issue by sethkor** [awslabs/goformation#68]
Hello,
Any idea on when the Fn::GetAtt intrinsic function shall be supported?
Cheers
Seth

**Comment by PaulMaddox** [comment]
This library now has support for using CloudFormation Intrinsic functions when composing CloudFormation templates - check out the examples in the README for details of how to use `cloudformation.GetAtt()` and others.

**Comment by StevenACoffman** [comment]
@PaulMaddox `Fn::GetAtt` intrinsic function is listed as unsupported here https://github.com/awslabs/goformation#aws-cloudformation-intrinsic-functions however, I see [fngetatt](https://github.com/awslabs/goformation/blob/master/intrinsics/fngetatt.go) code and this issue. 

mweagle/Sparta#97 have been avoiding adopting goformation for a year. Can you clarify the status?
