### ISSUE TITLE
Example usage of Outputs

### ISSUE THREAD

**Issue by kegsay** [awslabs/goformation#75]
New user here, seeing whether this is worth me using over troposphere.

I tried to add an Output to the template, but the godoc is rather opaque, [merely stating](https://godoc.org/github.com/awslabs/goformation/cloudformation#Template) `map[string]interface{}`. This is surprising since there [are documented fields](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html) for an `Output`, but this doesn't seem to be represented in goformation. The same isn't true for troposphere, which will fail (albeit at runtime) if you pass an invalid key (eg typoing `Descripption`).

Do you *really* expect people to be typing:
```go
template.Outputs["MyOutput"] = map[string]interface{}{
    "Description": "my desc",
    ....
}
```

I'm hoping I'm just missing the type definition somewhere, otherwise this is actually less safe than using troposphere :(

**Comment by devonartis** [comment]
I found your statement to be true ...

**Comment by xrn** [comment]
@rubenfonseca seems that this can be closed as well - I solved this 2 years ago :D

**Comment by rubenfonseca** [comment]
Super good to hear! Thank you for your help!
