### ISSUE TITLE
Support for "Ref" 

### ISSUE THREAD

**Issue by noamha** [awslabs/goformation#81]
Hi,

How can I create a reference to an object, for example:
```
    "Subnet" : {
      "Type" : "AWS::EC2::Subnet",
      "Properties" : {
        "VpcId" : { "Ref" : "VPC" },
        "CidrBlock" : "10.0.0.0/24",
        "AvailabilityZone": "us-east-1a",
        "MapPublicIpOnLaunch": true,
        "Tags" : [ {"Key" : "Name", "Value" : "Subnet-By-CF" } ]
      }
    }
```
The `cloudformation.AWSEC2Subnet` VpcId property only accepts string.

Thanks.

**Comment by PaulMaddox** [comment]
This library now has support for using CloudFormation Intrinsic functions when composing CloudFormation templates - check out the examples in the README for details of how to use `cloudformation.Ref()` and others.
