### ISSUE TITLE
Docs say S3Location.Version is optional, but models says it is required

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/goformation#87]
## Docs

https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3-location-object

## Model

https://github.com/awslabs/goformation/blob/master/generate/sam-2016-10-31.json#L197

**Comment by PaulMaddox** [comment]
The main problem here is that while CloudFormation has a published machine generated specification, SAM currently does not. The one in the Goformation repository was manually generated, and has no mechanism to keep it up to date.

We should reach out to @sanathkr to discuss options.

**Comment by sanathkr** [comment]
SAM has a JSON Schema spec, but it is still WIP - https://github.com/awslabs/serverless-application-model/tree/master/samtranslator/validator/sam_schema 

Needs more validation but we will eventually get it good shape.

**Comment by parsnips** [comment]
@sanathkr it's be super great to have this ready to be updated regularly. For example the SQSEvent would be a nice addition to goformation. What's the best way to move that forward? Will goformation generate with that json schema?

**Comment by sanathkr** [comment]
Unfortunately not. There is a JSON Schema but it isn't 100% complete - https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/validator/sam_schema/schema.json. We do continue to add new properties to the schema but some existing properties still need work

**Comment by nija-at** [comment]
Hello @sanathkr - has there been any progress on here in getting authoritative SAM schema published?

AWS CDK depends on the SAM schema to autogenerate its language bindings and any deviations in the handcrafted one here from what's published in the SAM in this repo is going to impact CDK users. Here's an example - https://github.com/aws/aws-cdk/issues/3841
