### ISSUE TITLE
Updates to CloudFormationResourceSpecification.json?

### ISSUE THREAD

**Issue by parsnips** [awslabs/goformation#91]
Looks like new event types for lambda's have been released but when `go generate` no new files have been touched. My guess is that the cloudformation specs have not been released yet.  @PaulMaddox who should be nudged to get that out?

**Comment by jason-riddle** [comment]
@parsnips It looks like this is already covered by [AWS::Lambda::EventSourceMapping](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html) which was updated on May 24, 2018.

I believe this change is covered here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

> AWS::Lambda::EventSourceMapping
The StartingPosition property is no longer required.

This Terraform PR ([pr/5024](https://github.com/terraform-providers/terraform-provider-aws/pull/5024)) seems to agree with this assumption as well.

> Amazon recently made it possible to have SQS events trigger Lambdas. See: https://aws.amazon.com/blogs/aws/aws-lambda-adds-amazon-simple-queue-service-to-supported-event-sources/ for more details.
>
> As part of this they specifically utilize CreateSourceEventMapping to describe the mapping between SQS and Lambda: https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html
>
> However, as part of this, they changed the StartingPosition message property from required to optional. You can see that it was previous required here: https://web.archive.org/web/20171222204154/https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html

**Comment by parsnips** [comment]
@jason-riddle thanks for the pointer!
